rootProject.name = "spring-guide"
include("creating-a-batch-service")
include("building-a-restful-web-service")
include("integrating-data")
include("managing-transactions")
include("validating-form-input")
include("messaging-with-redis")
include("messaging-with-rabbitmq")
include("spring-boot-kubernetes")
include("caching-data-with-spring")
include("producing-a-soap-web-service")
include("consuming-a-soap-web-service")
include("messaging-with-jms")